
# Path to the main MCP Host configuration file.
# This is needed so the evaluator can potentially start/use tool servers defined there.
# Use a relative path for the debug config.
mcp_host_config = "./debug_config.json"

# Directory containing the evaluation task files (e.g., task_research_and_summarize.txt).
tasks_dir = "eval_tasks"

# Path to the prompt template used for grading responses.
# You need to create this file (see step 2 below).
grading_prompt_path = "prompts/eval_grading_prompt.txt"

# Path where the evaluation results (JSON Lines format) will be saved.
output_path = "eval_results/results.jsonl"

# Maximum time (in seconds) allowed for a model to complete a single task.
task_timeout_secs = 180 # 10 minutes

# Maximum time (in seconds) allowed for a model to grade a single response.
grading_timeout_secs = 180 # 3 minutes

# List of providers and models to evaluate.
# Each entry will act as both a "performer" (running the task)
# and a "grader" (evaluating other models' responses).
# API keys are primarily expected via environment variables (e.g., OPENROUTER_API_KEY, GROQ_API_KEY)
# or a .env file, as set up in main.rs/main_repl.rs.
# You can optionally add `api_key = "..."` to override for a specific entry.

# --- Direct Providers ---

[[providers]]
name = "anthropic" # Direct Anthropic
model = "claude-3-7-sonnet-20250219" # Use specific ID

[[providers]]
name = "google" # Direct Google (Gemini)
model = "gemini-2.5-pro-exp-03-25" # Or gemini-2.5-pro if preferred/available

# [[providers]]
# name = "deepseek" # Direct DeepSeek
# model = "deepseek-chat" # Or deepseek-v3-0324


# Note: Llama 3.1 70B might not be directly available via a standard provider yet.
# Keeping Groq for a Llama 3 variant.
# [[providers]]
# name = "meta" # Hypothetical direct Meta provider
# model = "llama-3.1-70b-instruct"

# Note: Mistral Large might not be directly available via a standard provider yet.
# Using OpenRouter as a fallback for this one.
# [[providers]]
# name = "openrouter" # Fallback via OpenRouter
# model = "mistralai/mistral-large"

