# Model suggestions for AI providers
# These are used as fallbacks when no specific model is provided in the server configuration

[anthropic]
models = [
  "claude-3-opus-20240229",
  "claude-3-sonnet-20240229",
  "claude-3-haiku-20240307",
  "claude-3-5-sonnet-20240620",
  "claude-2.1",
  "claude-2.0",
  "claude-instant-1.2"
]

[openai]
models = [
  "gpt-4-1106-preview",
  "gpt-4-vision-preview",
  "gpt-4o",
  "gpt-4o-mini",
  "gpt-4-turbo",
  "gpt-4",
  "gpt-3.5-turbo"
]

[google-genai]
models = [
  "gemini-1.5-pro",
  "gemini-1.5-flash",
  "gemini-1.0-pro",
  "gemini-1.0-ultra"
]

[mistralai]
models = [
  "mistral-large-latest",
  "mistral-medium-latest",
  "mistral-small-latest",
  "open-mistral-7b"
]

[fireworks]
models = [
  "accounts/fireworks/models/llama-v3-70b",
  "accounts/fireworks/models/llama-v3-8b",
  "accounts/fireworks/models/mixtral-8x7b-instruct"
]

[together]
models = [
  "mistralai/Mixtral-8x7B-Instruct-v0.1",
  "meta-llama/Llama-2-70b-chat-hf",
  "togethercomputer/llama-2-70b-chat"
]